### ISSUE TITLE
Error updating plugin to 8.1.3 (2024-08-09)

### ISSUE THREAD

**Issue by mic-men** [opencast-ilias/OpenCast#338]
**Describe the bug**
Updating the plugin to version 2024-08-09 06:00 (git tag: 3236424d24f19c5a806722fc4ec40667a1763527 ) throws an error.

**To Reproduce**
1. Update plugin source as mentioned above
2. Run Composer - ok.
3. Do the php update on commandline as requested
`php setup/setup.php update --plugin Opencast -vv`
4.  Error is thrown:
`Get a confirmation from admin....                                          [OK]
Read client-id from data-directory....                                     [OK]
Can create files in '/var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/data/pr01'...[OK]
Can create files in '/var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3'...[OK]
The ilias.ini.php and client.ini.php are loaded...                         [OK]
The database object is initialized....                                     [OK]
PHP Fatal error:  Uncaught Error: Call to a member function quote() on null in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/Language/classes/Setup/class.ilSetupLanguage.php:198
Stack trace:
#0 /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/Language/classes/Setup/class.ilLanguagesInstalledAndUpdatedObjective.php(47): ilSetupLanguage->getInstalledLanguages()
#1 /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/Language/classes/Setup/class.ilLanguagesInstalledAndUpdatedObjective.php(63): ilLanguagesInstalledAndUpdatedObjective->getInstallLanguages()
#2 /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/src/Setup/CLI/ObjectiveHelper.php(56): ilLanguagesInstalledAndUpdatedObjective->getLabel()
#3 /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/src/Setup/CLI/UpdateCommand.php(108): ILIAS\Setup\CLI\UpdateCommand->achieveObjective()
#4 /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/libs/composer/vendor/symfony/console/Command/Command.php(298): ILIAS\Setup\CLI\UpdateCommand->execute()
#5 /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/libs/composer/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#6 /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/libs/composer/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#7 /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/libs/composer/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#8 /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/setup/cli.php(40): Symfony\Component\Console\Application->run()
#9 /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/setup/setup.php(42): require_once('...')
#10 {main}
  thrown in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/Language/classes/Setup/class.ilSetupLanguage.php on line 198
PHP Fatal error:  Uncaught Error: Call to a member function quote() on null in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/Language/classes/Setup/class.ilSetupLanguage.php:198
Stack trace:
#0 /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/Language/classes/Setup/class.ilLanguagesInstalledAndUpdatedObjective.php(47): ilSetupLanguage->getInstalledLanguages()
#1 /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/Language/classes/Setup/class.ilLanguagesInstalledAndUpdatedObjective.php(63): ilLanguagesInstalledAndUpdatedObjective->getInstallLanguages()
#2 /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/src/Setup/CLI/ObjectiveHelper.php(43): ilLanguagesInstalledAndUpdatedObjective->getLabel()
#3 [internal function]: ILIAS\Setup\CLI\UpdateCommand::ILIAS\Setup\CLI\{closure}()
#4 {main}
`

**Environment**
 - ILIAS version: 8.13
 - PHP version: PHP 8.0.30
 - Plugin version: 8.1.3 (2024-08-09)
 - Opencast version: 14.6

**Comment by mic-men** [comment]
Appearently the error occurs in a core ILIAS part _Services/Language/classes/Setup/class.ilSetupLanguage.php_ stating that _global $ilDB_ is null.
I don't understand it. PHP version is 8.0.30, Composer run without error.
Am I really the only one with this error?

**Comment by chfsx** [comment]
I can confirm this issue when trying to update the plugin separately (with the --plugin option). But this seems to be an issue in ILIAS core, I can reproduce this with every plugin and even with non existing ones (e.g. `php setup/setup.php update --plugin BlaBlaBla`)

**Comment by mic-men** [comment]
Ok, and I can confirm that it works without the --plugin option. We are normally very reluctant to the overall php setup call when we just want to update a plugin (if something fails the whole ILIAS might be unusable). Therefore until now I did not check without the option.
So we know that it is an issue in ILIAS core (but I'm still wondering why it worked two weeks ago and we didn't update ILIAS in the  meantime...).
Can we do something about it?

**Comment by chfsx** [comment]
> Can we do something about it?

The best way to report the problem is via mantis for the ILIAS core: https://mantis.ilias.de
You can link the tick here, then we have the reference.

**Comment by mic-men** [comment]
I made a bug report [in mantis](https://mantis.ilias.de/view.php?id=41905)

**Comment by chfsx** [comment]
@mic-men thanks a lot!

**Comment by mic-men** [comment]
According to mantis bug tracker the problem is fixed with ILIAS 8.15.
The issue remains open until confirmation by someone with this version.

**Comment by dagraf** [comment]
The issue opened in Mantis (https://mantis.ilias.de/view.php?id=41905) got fixed. Can someone confirm the fix of this issue her, too?

**Comment by dagraf** [comment]
@mic-men: Since you opened this issue, can you please test if it got fixed with the above mentioned core fix? Thank you!

**Comment by mic-men** [comment]
We confirn, that the issue has been resolved with ILIAS 8.15.
