### ISSUE TITLE
Settings tab not working for some series

### ISSUE THREAD

**Issue by okaufman** [opencast-ilias/OpenCast#369]
We had some series where we could not access the settings tab because of the following error:

Whoops\Handler\CallbackHandler::handle:398 2 Undefined array key "cast-view" in /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Model/PermissionTemplate/PermissionTemplate.php:24

It only happend to series that were at one time published on a video-portal and then again unpublished.

**To Reproduce**
There is no easy way to reproduce the issue.

**Expected behavior**
The settings tab should open when clicking on it

**Log**
```

[u1m51] [2024-09-02 17:58:32.726596] ilias3_unibe_root.ERROR: Whoops\Handler\CallbackHandler::handle:398 2 Undefined array key "cast-view" in /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Model/PermissionTemplate/PermissionTemplate.php:247#0 /var/www/ilias/Services/Init/classes/class.ilErrorHandling.php(459): Whoops\Run->handleError()
#1 /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Model/PermissionTemplate/PermissionTemplate.php(247): ilErrorHandling->handlePreWhoops()
#2 /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Model/Series/Series.php(86): srag\Plugins\Opencast\Model\PermissionTemplate\PermissionTemplate::getTemplateForAcls()
#3 /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastGUI.php(566): srag\Plugins\Opencast\Model\Series\Series->isPublishedOnVideoPortal()
#4 /var/www/ilias/Services/Repository/PluginSlot/class.ilObjectPluginGUI.php(172): ilObjOpenCastGUI->infoScreen()
#5 /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastGUI.php(191): ilObjectPluginGUI->executeCommand()
#6 /var/www/ilias/Services/UICore/classes/class.ilCtrl.php(203): ilObjOpenCastGUI->executeCommand()
#7 /var/www/ilias/Services/Repository/PluginSlot/class.ilObjPluginDispatchGUI.php(61): ilCtrl->forwardCommand()
#8 /var/www/ilias/Services/UICore/classes/class.ilCtrl.php(203): ilObjPluginDispatchGUI->executeCommand()
#9 /var/www/ilias/Services/UICore/classes/class.ilCtrl.php(178): ilCtrl->forwardCommand()
#10 /var/www/ilias/ilias.php(24): ilCtrl->callBaseClass()
#11 {main}
```

**Comment by okaufman** [comment]
I will create a PR for this issue
