### ISSUE TITLE
call database on null when using Plugin-API

### ISSUE THREAD

**Issue by okaufman** [opencast-ilias/OpenCast#384]
**Describe the bug**
When using the Plugin-API, I get this error
Call to a member function database() on null in /var/www/ilias-test/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Container/Init.php:127

**To Reproduce**
I try to initialise the series-API with this command, like it is in the docu:
xoctInternalAPI::getInstance()->series()

**Expected behavior**
I expect to get no error when using xoctInternalAPI::getInstance()->series()

**Screenshots**
<img width="1721" alt="Bildschirmfoto 2024-12-17 um 13 25 47" src="https://github.com/user-attachments/assets/ce189c67-8679-468d-96b0-09ddd97806ed" />

**Environment (please complete the following information):**
 - ILIAS version: 8.16
 - PHP version: 8.0
 - Plugin version: 8.2.8
 - Opencast version 16.7

**Log
```
[9d4nv] [2024-12-17 16:46:36.911509] ilias3_unibe_root.ERROR: Whoops\Handler\CallbackHandler::handle:398 0 Call to a member function database() on null in /var/www/ilias-test/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Container/Init.php:127#0 /var/www/ilias-test/libs/composer/vendor/pimple/pimple/src/Pimple/Container.php(118): srag\Plugins\Opencast\Container\Init::srag\Plugins\Opencast\Container\{closure}()
#1 /var/www/ilias-test/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Container/Container.php(28): Pimple\Container->offsetGet()
#2 /var/www/ilias-test/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Container/Init.php(138): srag\Plugins\Opencast\Container\Container->get()
#3 /var/www/ilias-test/libs/composer/vendor/pimple/pimple/src/Pimple/Container.php(118): srag\Plugins\Opencast\Container\Init::srag\Plugins\Opencast\Container\{closure}()
#4 /var/www/ilias-test/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Container/Container.php(28): Pimple\Container->offsetGet()
#5 /var/www/ilias-test/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Service/class.xoctSeriesAPI.php(45): srag\Plugins\Opencast\Container\Container->get()
#6 /var/www/ilias-test/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Service/class.xoctSeriesAPI.php(55): xoctSeriesAPI->__construct()
#7 /var/www/ilias-test/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Service/class.xoctInternalAPI.php(42): xoctSeriesAPI::getInstance()
#8 /var/www/ilias-test/Customizing/global/plugins/Origins2/src/helper/unibeEventPodcastOriginHandler.php(53): xoctInternalAPI->series()
#9 /var/www/ilias-test/Customizing/global/plugins/Origins2/src/origins/session/unibeSessionOrigin.php(77): iLub\Plugin\Origin\helper\unibeEventPodcastOriginHandler->__construct()

```

**Comment by okaufman** [comment]
i will make a PR for this
